#!/usr/bin/env python
import sys
import json

data = json.loads(sys.stdin.read())
total_infected = sum([int(i['confirmed'].replace(",","")) for i in data.values()])

with open('states.txt', 'r') as f:
    states = [state.strip() for state in f.readlines()]

print(f"Total US cases : {total_infected:,}")

for state in states:
    print(f"Total in {state}: {data[state]['confirmed']}")
